/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppControls: typeof import('./src/components/AppControls.vue')['default']
    AppControlsComfyUI: typeof import('./src/components/AppControls-ComfyUI.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Checkpoints: typeof import('./src/components/controls/Checkpoints.vue')['default']
    ClipShiftDenoise: typeof import('./src/components/controls/ClipShiftDenoise.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dimensions: typeof import('./src/components/controls/Dimensions.vue')['default']
    Dock: typeof import('primevue/dock')['default']
    Editor: typeof import('primevue/editor')['default']
    GuidanceSteps: typeof import('./src/components/controls/GuidanceSteps.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loras: typeof import('./src/components/controls/Loras.vue')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    PromptEditor: typeof import('./src/components/controls/PromptEditor.vue')['default']
    PromptNegative: typeof import('./src/components/controls/PromptNegative.vue')['default']
    PromptPositive: typeof import('./src/components/controls/PromptPositive.vue')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    SamplerScheduler: typeof import('./src/components/controls/SamplerScheduler.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Seed: typeof import('./src/components/controls/Seed.vue')['default']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Styles: typeof import('./src/components/controls/Styles.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TextEncoders: typeof import('./src/components/controls/TextEncoders.vue')['default']
    Vaes: typeof import('./src/components/controls/Vaes.vue')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
